#!/usr/bin/ruby
#
# Copyright 2014 Peter van Zetten
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'hiera'
require 'yaml'

# Query scope
scope = { '::fqdn' => ARGV[0] }

# Hiera interface
config = YAML::load_file('/etc/puppet/hiera-enc/hiera-enc.yaml')

#Comment out to enable debug logging.
config[:logger] = 'noop'

hiera = Hiera.new(:config => config)
parameters = hiera.lookup('parameters', nil, scope)
environment = hiera.lookup('environment', nil, scope)

result = {}

if parameters
    result['parameters'] = parameters
end

if environment
    result['environment'] = environment
end

if result.has_key?('environment') || result.has_key?('parameters')
    puts result.to_yaml
end
